### ISSUE TITLE
Update metadata some more

### ISSUE THREAD

**Issue by ocdtrekkie** [dwrensha/gitweb-sandstorm#11]
It'd be nice to update the description to mention web publishing, and also update the changelog for the app. I wouldn't re-submit for now, but I figured I'd highlight these things:

- The changelog is not updated, which is sad because we have new features.
- The new features in question is worthwhile enough that they should probably be noted in the description.
- The screenshot for this app is very small. While it should be well-compressed to ensure it doesn't bloat the package size, people have complained about unreadably-small screenshots on the market before: https://github.com/sandstorm-io/sandstorm-app-market/issues/66

**Comment by dwrensha** [comment]
Sounds good to me. I'd be happy to merge such an update if you or @abliss want to submit a pull request.

**Comment by ocdtrekkie** [comment]
#12 satisfies this for me. I wouldn't mind new screenshots at some point, but I'm happy.
